package cz.rodro.entity;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;
import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.core.authority.SimpleGrantedAuthority;
import org.springframework.security.core.userdetails.UserDetails;

import java.util.Collection;
import java.util.List;

/**
 * Entity representing a system user.
 * <p>
 * This class stores user authentication and identity information. It implements the
 * {@link UserDetails} interface, allowing it to be used directly by Spring Security
 * for authentication and authorization purposes.
 * </p>
 */
@Entity(name = "user")
@Getter
@Setter
public class UserEntity implements UserDetails {

    /**
     * Unique identifier for the user.
     * <p>
     * This field serves as the primary key and is auto-generated by the database.
     * </p>
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private long userId;

    /**
     * The primary email address of the user.
     * <p>
     * This field is mandatory and must be unique across all users in the system.
     * It is used as the {@link #getUsername()} for Spring Security authentication.
     * </p>
     *  * @author Dimitri Bodzewicz
     *  * @version 1.0
     */
    @Column(nullable = false, unique = true)
    private String email;

    /**
     * The hashed password of the user.
     * <p>
     * This field is mandatory and stores the securely hashed version of the user's password.
     * </p>
     */
    @Column(nullable = false)
    private String password;

    /**
     * The full, displayable name of the user.
     * <p>
     * This field is mandatory.
     * </p>
     */
    @Column(nullable = false)
    private String fullName;

    /**
     * Flag indicating if the user has administrative privileges.
     * <p>
     * Defaults to {@code false} (standard user). If {@code true}, the user is granted the ROLE_ADMIN authority.
     * </p>
     */
    @Column(nullable = false)
    private boolean admin = false;

    // --- UserDetails Interface Implementations ---

    /**
     * Returns the username used to authenticate the user.
     * <p>
     * In this application, the {@code email} field serves as the username.
     * </p>
     * @return The user's email address.
     */
    @Override
    public String getUsername() {
        return email;
    }

    /**
     * Returns the authorities granted to the user.
     * <p>
     * Based on the {@code admin} flag, the user is assigned either the "ROLE_ADMIN" or "ROLE_USER" authority.
     * </p>
     * @return A collection containing the user's granted security authority.
     */
    @Override
    public Collection<? extends GrantedAuthority> getAuthorities() {
        GrantedAuthority grantedAuthority = new SimpleGrantedAuthority("ROLE_" + (admin ? "ADMIN" : "USER"));
        return List.of(grantedAuthority);
    }

    /**
     * Indicates whether the user's account has expired.
     * <p>
     * Always returns {@code true} as account expiration is not currently implemented.
     * </p>
     * @return {@code true} if the account is valid (non-expired).
     */
    @Override
    public boolean isAccountNonExpired() {
        return true;
    }

    /**
     * Indicates whether the user is locked or unlocked.
     * <p>
     * Always returns {@code true} as account locking is not currently implemented.
     * </p>
     * @return {@code true} if the account is not locked.
     */
    @Override
    public boolean isAccountNonLocked() {
        return true;
    }

    /**
     * Indicates whether the user's credentials (password) have expired.
     * <p>
     * Always returns {@code true} as password expiration policy is not currently implemented.
     * </p>
     * @return {@code true} if the credentials are valid (non-expired).
     */
    @Override
    public boolean isCredentialsNonExpired() {
        return true;
    }

    /**
     * Indicates whether the user is enabled or disabled.
     * <p>
     * Always returns {@code true} as enabling/disabling is not currently implemented.
     * </p>
     * @return {@code true} if the user is enabled.
     */
    @Override
    public boolean isEnabled() {
        return true;
    }
}