const causeOfDeathLabels = {
    TUBERCULOSIS: "Gruźlica",
    CHOLERA: "Cholera",
    SMALLPOX: "Ospa prawdziwa",
    MEASLES: "Odra",
    MUMPS: "Świnka",
    PNEUMONIA: "Zapalenie płuc",
    INFLUENZA: "Grypa",
    MALARIA: "Malaria",
    PLAGUE: "Dżuma",
    TYPHUS: "Tyfus plamisty",
    TYPHOID_FEVER: "Dur brzuszny",
    LEPROSY: "Trąd",
    DYSENTERY: "Czerwonka",
    SCARLET_FEVER: "Szkarlatyna",
    DIPHTHERIA: "Błonica",
    POLIO: "Polio",
    RABIES: "Wścieklizna",
    HEPATITIS_A: "WZW typu A",
    HEPATITIS_B: "WZW typu B",
    HEPATITIS_C: "WZW typu C",
    SYPHILIS: "Kiła",
    GONORRHEA: "Rzeżączka",
    HIV_AIDS: "HIV/AIDS",
    COVID_19: "COVID-19",

    DIABETES: "Cukrzyca",
    CANCER: "Nowotwór",
    ASTHMA: "Astma",
    HYPERTENSION: "Nadciśnienie",
    STROKE: "Udar mózgu",
    HEART_DISEASE: "Choroba serca",
    ALZHEIMERS_DISEASE: "Choroba Alzheimera",
    PARKINSONS_DISEASE: "Choroba Parkinsona",

    MELANCHOLIA: "Melancholia",
    HYSTERIA: "Histeria",
    EPILEPSY: "Padaczka",
    DEMENTIA: "Demencja",
    SCHIZOPHRENIA: "Schizofrenia",
    MANIA: "Mania",
    SUICIDE: "Samobójstwo",

    BLACK_LUNG_DISEASE: "Pylica węglowa",
    SILICOSIS: "Pylica krzemowa",
    LEAD_POISONING: "Zatrucie ołowiem",
    ASBESTOSIS: "Azbestoza",
    STARVATION: "Głód",
    DEHYDRATION: "Odwodnienie",

    ALCOHOLISM: "Alkoholizm",
    DRUG_OVERDOSE: "Przedawkowanie narkotyków",
    TOBACCO_RELATED_DISEASE: "Choroba związana z paleniem",

    ACCIDENT: "Wypadek",
    FALL: "Upadek",
    DROWNING: "Utonięcie",
    BURNS: "Poparzenia",
    HOMICIDE: "Zabójstwo",
    WAR_WOUNDS: "Rany wojenne",
    COMBAT_DEATH: "Śmierć w walce",
    EXECUTION: "Egzekucja",
    TERRORIST_ATTACK: "Atak terrorystyczny",

    OLD_AGE: "Starość",
    CONSUMPTION: "Suchoty",
    DROPSY: "Puchlina wodna",
    ERGOTISM: "Zatrucie sporyszem",
    SPANISH_FLU: "Hiszpanka",
    ENGLISH_SWEATING_SICKNESS: "Angielska potówka",
    FEVER: "Gorączka",
    UNKNOWN: "Nieznana przyczyna",
    OTHER: "Inna przyczyna"
};

export default causeOfDeathLabels;